### ISSUE TITLE
Double Tap To wake up

### ISSUE THREAD

**Issue by GCgpx** [Euphoria-OS/Bug-tracker#10]
http://puu.sh/hSSlo/a766e39112.png
I've Stock Kernel

**Comment by mitchelldavis44** [comment]
First of all, we can't help you unless you follow the proper procedure.  You need to fill this out:

Do you use Xposed framework? If yes, do not even bother reporting.
Uninstall Xposed(&reboot), check if the bug you're trying to report still
exists and then proceed. Otherwise,your report will be declared invalid.

Your device:

Which ROM version are you using? (provide download link)

What kernel are you using - included in the ROM or from another source?
(provide xda/download link)

What steps will reproduce the problem?
1.
2.
3.

What is the expected result? What do you see instead?

Is the result seen after a clean flash too?

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.

Second of all, if you have a n5 and installed the latest test build that I released on the 16th you need to read the announcement.  In the announcement I said that there would be no kernel features as it was a test build and it was basically a completely stock kernel meaning no features, that includes double tap to wake.
