### ISSUE TITLE
Fat side scrollbars in system and apps

### ISSUE THREAD

**Issue by eurochild-dps** [Euphoria-OS/Bug-tracker#15]
I remember Altaf telling me that a commit causes this.

![screenshot_2015-06-02-21-12-20](https://cloud.githubusercontent.com/assets/7645326/7943301/6cde8db6-096c-11e5-909e-ed6d6b506039.png)

![screenshot_2015-06-02-21-12-41](https://cloud.githubusercontent.com/assets/7645326/7943302/6ce37fb0-096c-11e5-88b0-ee9aed967fc9.png)

**Comment by dexmc** [comment]
confirmed. @Altaf-Mahdi can you take a look please

**Comment by Altaf-Mahdi** [comment]
I'm sure this is a 5.1 thing, anyone tested this on stock 5.1?

**Comment by eurochild-dps** [comment]
@Altaf-Mahdi  today i had the chance to see a stock 5.1.1 mako and the issue is not there.

**Comment by Altaf-Mahdi** [comment]
@eurochild-dps did you test titanium backup on stock 5.1 because those fat bars means the dev enabled fast scroll in the app, the reason you don't see this in stock 5.1 manage apps screen is because Google didn't enable fast scroll.

We could easily fix this issue by reverting https://github.com/Euphoria-OS/android_packages_apps_Settings/commit/3dde2bbd28d44780e352d03ed1d826d1ab440ecd but that would mean that we need to remove fast scroll from expanded desktop settings too, for me this isn't a bug and its something Google changed in the scroll design which has made the fast scroll bar look like this.

This is with that patch reverted
![screenshot_2015-07-03-20-28-22](https://cloud.githubusercontent.com/assets/2896498/8504067/2c6050c6-21c2-11e5-9724-318e63bae563.png)

The only thing I will fix is to make it so it auto hides. http://eosgerrit.ddns.net:51250/#/c/6138/

**Comment by eurochild-dps** [comment]
@Altaf-Mahdi I think its ok that way. better than those fat bars
